export const ActionType = {
    SET_IS_VISIBLE_SIGN_IN_MODAL: 'setIsVisibleSignInModal',
    SET_IS_VISIBLE_SIGN_UP_MODAL: 'setIsVisibleSignUpModal',
    SET_IS_VISIBLE_WAIT_MODAL: 'setIsVisibleWaitModal',
    SET_SET_ERROR_MESSAGES: 'setErrorMessages',
    SET_IS_AUTHENTICATED: 'setIsAuthenticated',
    SET_FRIENDS: 'setFriends',
    SET_LOADING: 'setLoading',
    SET_CURRENT_USER: 'setCurrentUser',
    SET_FRIEND: 'setFriend',
    SET_PROFILE_IMAGE: 'setProfileImage',
    SET_PREVIEW_PROFILE_IMAGE: 'setPreviewProfileImage',
    SET_BIRTHDAY_IMAGE: 'setBirthdayImage',
    SET_PREVIEW_BIRTHDAY_IMAGE: 'setPreviewBirthdayImage',
}
